### ISSUE TITLE
请问windows 如何安装奇门api部分 ? 

### ISSUE THREAD

**Issue by dafa168** [bububa/opentaobao#2]
windows尝试了 bin下的两个脚本，都报错了

centos 也是报错了。
[root@centos bin]# ./downloader 
bash: ./downloader: cannot execute binary file
[root@centos bin]# ./generator 
bash: ./generator: cannot execute binary file

**Comment by dafa168** [comment]
找到方法了。

**Comment by bububa** [comment]
downloader 和 generator 可以 通过 make tools 构建.

奇门API 在 github.com/bububa/opentaobao/api/qimen 下

**Comment by dafa168** [comment]
好的。谢谢老哥。
